version: '3.8'
services:
  transfer:
    image: 'dutchcoders/transfer.sh:latest'
    restart: unless-stopped
    ports:
      - '3210:8080'
    volumes:
      - './data:/data'
    environment:
      - BASEDIR=/data
      - PROVIDER=local
      - MAX_UPLOAD_SIZE=5368709120
      - PURGE_DAYS=14
      - PURGE_INTERVAL=1
      - RATE_LIMIT=10
      - WEB_PATH=/web
    healthcheck:
      test:
        - CMD
        - wget
        - '--spider'
        - '-q'
        - 'http://localhost:8080/'
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  transfer-data: null